---
# Common features for all linux servers

- name: Install ntp
  apt: name=ntp state=present
  tags: ntp

- name: Configure ntp file
  template: src=ntp.conf.t1 dest=/etc/ntp.conf backup=yes
  tags: ntp
  notify: restart ntp
  become: true

- name: Start the ntp service
  service: name=ntp state=started enabled=yes
  tags: ntp


- name: Install vim
  apt: name=vim state=present
  tags: vim

- name: Configure vim
  template: src=vimrc.t1 dest=/etc/vim/vimrc owner=root group=root mode=0644
  tags: vim

- name: Install byobu
  apt: name=byobu state=present
  tags: byobu
